### ISSUE TITLE
valor不生效

### ISSUE THREAD

**Issue by yuanjinkunlou** [kingyue737/volar-plugin-vue-router#1]
我配置了volar.config.js，也重新启动了volar，但是没生效
![image](https://github.com/kingyue737/volar-plugin-vue-router/assets/126596599/d5f7bd44-1d73-410c-bf2d-7ff2c8ae09b1)
![image](https://github.com/kingyue737/volar-plugin-vue-router/assets/126596599/67eac45b-d9fe-4ede-9270-1193af861bf5)

**Comment by kingyue737** [comment]
加个`default`
```js
const route = require('volar-plugin-vue-router').default
```

如果你的操作系统是windows，那必须要把volar升级到v1.7 pre-release。因为1.6以下有bug，不会读取`volar.config.js` https://github.com/volarjs/volar.js/issues/36 。
并且升级到v1.7后，要把`plugins`改为`services`,这是volar的一个breaking change:
```js
module.exports = {
  services: [
    route(),
  ],
}
```
